# Generated by Django 3.2.18 on 2023-03-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20230320_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
